### ISSUE TITLE
Add support for VS 2017

### ISSUE THREAD

**Issue by Rominitch** [atlaste/CPPCoverage#14]
Currently, published VSIX doesn't support VisualStudio 2017 Community.

Can you add it ?

**Comment by atlaste** [comment]
I currently don't have access to a VS2017 installation.

Still, I can see no reason why it shouldn't work. The only thing you need to do is to install the VS SDK (it's in the installer), change the VISX settings and compile. That's it.

**Comment by Rominitch** [comment]
Hi,
I tried to make job with VisualStudio 2017 Community.
I spend many time to migrate to 4.7 NET (latest I have on my computer) and relink all package.

Compilation and installation is OK now !

During execution:
- Report is OK !
- BUT I have lost your colored text background  (green = cover, ...).

**Comment by atlaste** [comment]
Nice!

> BUT I have lost your colored text background (green = cover, ...).

Congrats, you stumbled upon one of the worst documented pieces of the VS API, which apparently has changed in the new VS version :-( It's really a shame, because the API itself is great.

Anyways, let's see if we can easily fix this:

1. What happens if you restart VS / re-open the file? Is the color there? That's unfortunately normal behavior: adornment's are triggered the moment a file is rendered, and so far I haven't found a way around this. 
2. If that doesn't work, it's probably rendered, but in the wrong z-layer. In CodeCoverageFactory.cs, you'll find [Order(Before = PredefinedAdornmentLayers.BraceCompletion)]. You can try to simply remove this attribute and see if it works.

**Comment by Rominitch** [comment]
I will try to find solution.

I think I will fork project into my space.

**Comment by atlaste** [comment]
If you do find it, please let me know.

**Comment by Rominitch** [comment]
I published on my GitHub the support of VS 2017.

I tried all your solution without success.

**Comment by Rominitch** [comment]
I created from scratch Adornment component to compare with current version.

After copied:
[Order(After = PredefinedAdornmentLayers.Selection, Before = PredefinedAdornmentLayers.Text)]

It's work.

You have solution in my GitHub.

**Comment by atlaste** [comment]
Hmm that's the default right? That gives issues with selection, that is: if you select text, the green/red stuff stays...

I recall asking about this on SO some time before... Here's some more information, perhaps it is of help: https://stackoverflow.com/questions/37720856/visual-studio-adornment-in-front-of-text-interferes-with-selection .

**Comment by Rominitch** [comment]
My result is 
![image](https://user-images.githubusercontent.com/29762419/27711314-23291ae4-5d23-11e7-8ab2-b7c169983568.png)

Looking fine ! (But I'm agree with you I demand rendering AFTER selection ...)

**Comment by atlaste** [comment]
Unfortunately, it's probably a matter of trial and error to make this look great. :-)
