### ISSUE TITLE
Visual Studio 2010 / Windows 2003 server

### ISSUE THREAD

**Issue by melnaquib-aurea** [atlaste/CPPCoverage#22]
Will this build under 2010?

**Comment by atlaste** [comment]
Hmm... Yes and no. Let me explain.

Yes: The debugging API is stable since VS2005. Also, the csproj and sln files are not out-of-the-box working for VS2010, but should be portable. I cannot recall using specific C++11 features, so it should work using VS2010 just fine (just make a new SLN and CSPROJ that reflect the CSPROJ/SLN of the solution).

No: it's not designed to run using VS2010; we implemented it to work on VS2015 and nowadays on 2017. So no support...

If you plan to run it on a server, you might as well just grab the executables of course.

**Comment by melnaquib-aurea** [comment]
executables refuses it run! not a valid win32 app on windows server 2003! that's why I thougt I might build it from code.
just want to run it as EXE, not on VS
, like;
c:\myprj\cppcoverage.exe myapp.exe -output_report_dir=./output

**Comment by atlaste** [comment]
Sorry to hear that, it probably has to do with missing c++ runtimes? I don't have a win2003 system here, so I cannot test it.

Regardless, as I said I see no immediate reason why compiling from source shouldn't work, even though I haven't tested it.
