### ISSUE TITLE
VS 2019 Issue

### ISSUE THREAD

**Issue by aday12345** [atlaste/CPPCoverage#28]
- installed the plugin.
- ran my unit tests
- right clicked on the unit test project and clicked 'Run code coverage' and nothing happened
- closed all tab and reopened code file the was being tested and coverage info
- checked coverage report window and no info
- closed vs2019 and reopened to try process again and found 'Run code coverage' context menu  
  item is now missing

this is a c# project built with netcore 3.0 with the latest vs release

**Comment by atlaste** [comment]
Yea the reason is because this version only supports C++ (or actually: native code).

We actually have a first prototype for C# at the moment, that we're going to finalize once our new C++ implementation is finished. If you like i can give you a heads up at that time, should be one or two months from now. Just send me a mail at info@nubilosoft.com if your interested.

**Comment by aday12345** [comment]
Yes i am, and i sent you an email.

Thanks
